FROM 745892955196.dkr.ecr.us-east-1.amazonaws.com/docker-hub/library/golang:1.25

WORKDIR /workspace

# copy modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# cache modules
RUN go mod download
