name: Build Docker image

author: podinfo maintainers
description: Build and publish the podinfo images to ECR.

inputs:
  image_repository:
    description: "Full image repository to push the build to"
    required: true

outputs:
  image_tag:
    description: "Tag assigned to the built image"
    value: ${{ steps.prep.outputs.VERSION }}
  image_repository:
    description: "Image repository used for the build"
    value: ${{ inputs.image_repository }}

runs:
  using: composite
  steps:


    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.25.x


    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Get version from tag
      id: prep
      shell: bash
      run: |
        VERSION=sha-${GITHUB_SHA::8}
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF/refs\/tags\//}
        fi
        echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        echo "REVISION=${GITHUB_SHA}" >> $GITHUB_OUTPUT

    - name: Update image tag for environment
      shell: bash
      run: |
        ./.github/scripts/update-version-go.sh "${{ steps.prep.outputs.VERSION }}"

    - name: Generate images meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ inputs.image_repository }}
        tags: |
          type=raw,value=${{ steps.prep.outputs.VERSION }}
          type=raw,value=latest

    - name: Publish base image
      uses: docker/build-push-action@v6
      with:
        push: true
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        platforms: linux/amd64
        file: ./Dockerfile.base
        tags: ${{ inputs.image_repository }}-base:latest
        cache-from: type=gha,scope=release-base
        cache-to: type=gha,scope=release-base,mode=max


    - name: Publish docker image
      uses: docker/build-push-action@v6
      id: build-push
      with:
        sbom: true
        provenance: true
        push: true
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile.xx
        build-args: |
          REVISION=${{ steps.prep.outputs.REVISION }}
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha,scope=release-multiarch
        cache-to: type=gha,scope=release-multiarch,mode=max



    - name: Generate signed provenance attestation
      uses: actions/attest-build-provenance@v3
      with:
        subject-name: ${{ env.IMAGE_REPOSITORY }}
        subject-digest: ${{ steps.build-push.outputs.digest }}

    - name: Publish Build info With JFrog CLI
      env:
        JFROG_CLI_BUILD_NAME: podinfo
        # JFrog organization secret
        JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
      shell: bash
      run: |
        # Collect environment variables for the build
        jf rt build-collect-env

        # Collect VCS details from git and add them to the build
        jf rt build-add-git

        # Publish build info
        jf rt build-publish
