name: Build Docker image

author: podinfo maintainers
description: Build and publish the podinfo images to ECR.

inputs:
  image_repository:
    description: "Full image repository to push the build to"
    required: true

outputs:
  image_tag:
    description: "Tag assigned to the built image"
    value: ${{ steps.prep.outputs.VERSION }}
  image_repository:
    description: "Image repository used for the build"
    value: ${{ inputs.image_repository }}

runs:
  using: composite
  steps:

    - name: Configure AWS credentials for ECR
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: us-east-1

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.25.x

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Prepare
      id: prep
      shell: bash
      run: |
        VERSION=sha-${GITHUB_SHA::8}
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF/refs\/tags\//}
        fi
        echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        echo "REVISION=${GITHUB_SHA}" >> $GITHUB_OUTPUT

    - name: Generate images meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ inputs.image_repository }}
        tags: |
          type=raw,value=${{ steps.prep.outputs.VERSION }}
          type=raw,value=latest

    - name: Publish multi-arch image
      uses: docker/build-push-action@v6
      with:
        sbom: true
        provenance: true
        push: true
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile.xx
        build-args: |
          REVISION=${{ steps.prep.outputs.REVISION }}
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha,scope=release-multiarch
        cache-to: type=gha,scope=release-multiarch,mode=max

    - name: Publish base image
      uses: docker/build-push-action@v6
      with:
        push: true
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        platforms: linux/amd64
        file: ./Dockerfile.base
        tags: ${{ inputs.image_repository }}-base:latest
        cache-from: type=gha,scope=release-base
        cache-to: type=gha,scope=release-base,mode=max
